apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: llmops
  labels:
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app: redis
